name: Deploy Heroku
'on':
  push:
    branches:
      - main
  workflow_dispatch: null
jobs:
  test: null
  runs-on: ubuntu-latest
  steps:
    - uses: action/checkout@v3
    - name: Install dependencies
      run: pip install -r requirements.txt pip install flake8 pytest
    - name: Run tests
      run: make test
